### ISSUE TITLE
Naming of the library

### ISSUE THREAD

**Issue by kMutagene** [Freymaurer/Fake.Extensions.Release#1]
Not sure if the `ReleaseNotes.FAKE` namespace is the best to use, as FAKE already has the [`Fake.Core.ReleaseNotes`](https://www.nuget.org/packages/Fake.Core.ReleaseNotes/5.20.4-alpha.1642) namespace. I would suggest something more focused on the release draft functionality of this library, while clearly stating that this is a third party extension of the FAKE namespace, e.g.:

```Fake.Extensions.ReleaseDraft```

or, using your github handle as top level namespace like [`BlackFox.Fake.BuildTask`](https://www.nuget.org/packages/BlackFox.Fake.BuildTask/):

```freymaurer.Fake.ReleaseDraft```

**Comment by Freymaurer** [comment]
Done!
