### ISSUE TITLE
Exclude "Bump Release Notes" & "Merge PR" commits from Release Notes updates

### ISSUE THREAD

**Issue by omaus** [Freymaurer/Fake.Extensions.Release#4]
Commits that are only Merge commits or such that only handle the Release Notes themselves (e.g. "Bump Release Notes" etc.) should be excluded from the Release Notes update task as they clutter the commit list with no useful information and thus decrease readability.

**Comment by Freymaurer** [comment]
This is already done:
![image](https://github.com/Freymaurer/Fake.Extensions.Release/assets/39732517/20e0db36-cdb4-42a7-a1e4-c23caded5fb4)

**Comment by omaus** [comment]
1. I think 2 exact strings are a bit too specific, thus I would suggest a Regex pattern.
2. PR Merge commits are not excluded right now, are they?

**Comment by Freymaurer** [comment]
Feel free to open a PR
